import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SIGN_IN_URL, SIGN_UP_URL } from "@/lib/auth-routes";
import { clerkAppearance } from "@/lib/clerk-appearance";
import { DEFAULT_THEME, THEME_STORAGE_KEY } from "@/components/theme/theme-constants";
import { ThemeProvider } from "@/components/theme/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitScript = `
  (() => {
    try {
      const theme = localStorage.getItem("${THEME_STORAGE_KEY}") === "light" ? "light" : "${DEFAULT_THEME}";
      document.documentElement.dataset.theme = theme;
      document.documentElement.classList.toggle("light", theme === "light");
      document.documentElement.classList.toggle("dark", theme === "dark");
      document.documentElement.style.colorScheme = theme;
    } catch {
      document.documentElement.dataset.theme = "${DEFAULT_THEME}";
      document.documentElement.classList.add("${DEFAULT_THEME}");
      document.documentElement.style.colorScheme = "${DEFAULT_THEME}";
    }
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme={DEFAULT_THEME}
      className={`${geistSans.variable} ${geistMono.variable} ${DEFAULT_THEME} h-full`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className={`${geistSans.className} flex min-h-full flex-col antialiased`}>
        <ClerkProvider
          appearance={clerkAppearance}
          afterSignOutUrl={SIGN_IN_URL}
          signInUrl={SIGN_IN_URL}
          signUpUrl={SIGN_UP_URL}
        >
          <ThemeProvider>{children}</ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
